name: Schemathesis.io reporting demo

on:
  schedule:
    - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  kcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'

      - run: poetry install

      - name: Run wafp
        env:
          SCHEMATHESIS_REPORT: 'true'
          SCHEMATHESIS_TOKEN: ${{ secrets.SCHEMATHESIS_TOKEN }}
        run: poetry run wafp schemathesis:Fast kubernetes_kcp --output-dir=./artifacts

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
